name: Release
on:
  push:
    branches:
      - master
jobs:
  common:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
        working-directory: ./common
      - name: Test
        run: npm test
        working-directory: ./common
      - name: Build
        run: npm run build
        working-directory: ./common
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./common/package.json
  server:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        working-directory: ./server
      - name: Install
        run: npm install
        working-directory: ./server
      - name: Test
        run: npm test
        working-directory: ./server
      - name: Build
        run: npm run build
        working-directory: ./server
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true 
      - name: Deploy to gcloud
        run: gcloud app deploy
        working-directory: ./server
  functions:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    needs: common
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        working-directory: ./server
      - name: Install
        run: npm install
        working-directory: ./functions
      - name: Test
        run: npm test
        working-directory: ./functions
      - name: Build
        run: npm run build
        working-directory: ./functions
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true 
      - name: Deploy functions to gcloud
        run: |
            gcloud functions deploy computeScore --trigger-topic vote-trigger --runtime nodejs10
            gcloud functions deploy registerUser --trigger-event providers/firebase.auth/eventTypes/user.create --trigger-resource plaudio --runtime nodejs10
        working-directory: ./functions
