name: Release

on:
  push:
    tags: v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
        working-directory: ./common
      - name: Build
        run: npm run build
        working-directory: ./common
      - name: HMMMM
        env: NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: echo $NPM_TOKEN
      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
        working-directory: ./common
